language: java
jdk: oraclejdk8
script: "./gradlew build"
deploy:
  api_key:
    secure: eEmfooW/xeTjumc0rW8/jRY5YgQYU0YworHiluCcICfCdsF5fsRGgJVIqzf9Wa3oVwYjnAFWper6D01Zk8gv45UJeWHfrbTFbIxbLPP04FDPYN4fwnpIyIOE/tnheM+lypu1mI1UHRD0iS35b4Cbs9y1IY5sbWDkZt74DYEPh/OhfUHvMk9J8f3iOX3zJgL60zvG7xxNWS2e9pt1z03zCNCS6SlpPWMb0RKpdx1QDWbuNKyxNENpOKQtL1PSHPU7IW/JdODBtD/+kOuNxvRBV6OcSeU7uODWhow9L8iimcr2u+bPaFNMPr9/XwqhnEDvTx9cN3kZcFH4lQBReJ+Oa197YXDWtAlresOae/gCqN3R2P/H5W3Ni2dHhcPVlc13yyhQK539Kr2GdIX/OEZIrYxnaxsLgixNMuBptjDnLyKCzE4F0qZAoglwXYKMaunlROoeoAL++Qfidg9KnRSi7br8YD4DvxKCMLIGLkySqcUtV8sB0/Waq4ClXBWRSxX/1/WT9eTZ2cYZM2+FCRMP+cQGbGp3ITVMfwOA1dW+d12wygWJajrGHx6dEll3AQuGDF0TRxpEtUMpSi3MkFHpkD4Dw3sx/QELkET1Fg8S7ePyYn6kr8ubCOiSKa6VxhDpyNMAdwii3TjDaxx3eS6P1S++1jPkCCSiLQNLSlhEpd0=
