sudo: required
language: java
jdk: oraclejdk8
script: "./gradlew buildAll"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - frontend/.gradle/nodejs
    - frontend/.gradle/npm
    - frontend/node_modules
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)